import type { Metadata } from 'next';
import font from 'next/font/local';
import { twMerge as twm } from 'tailwind-merge';
import Navbar from '@/components/Navbar';
import SectionGetInTouch from '@/components/GetInTouch';

import './globals.css';

const generalSans = font({
  src: [
    {
      path: '../public/fonts/GeneralSans-Regular.ttf',
      style: 'normal',
      weight: '400',
    },
    {
      path: '../public/fonts/GeneralSans-Medium.ttf',
      style: 'normal',
      weight: '500',
    },
    {
      path: '../public/fonts/GeneralSans-Semibold.ttf',
      style: 'normal',
      weight: '600',
    },
    {
      path: '../public/fonts/GeneralSans-Bold.ttf',
      style: 'normal',
      weight: '700',
    },
  ],
  variable: '--font-general-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={twm(`${generalSans.variable}`)}>
      <body className={generalSans.className}>
        <Navbar />
        <main>{children}</main>
        <SectionGetInTouch />
      </body>
    </html>
  );
}
